# SPDX-FileCopyrightText: 2026 INTERCHAINED LLC
# SPDX-License-Identifier: MIT
"""Render bench/compare.py JSON into docs/BENCHMARKS.md.

Every sentence of judgement on the page is COMPUTED from the numbers in the
JSON — including where NEDB trails. Nothing here is hand-written marketing.
"""
from __future__ import annotations

import json
import sys
from typing import Any, Dict, List, Optional

PHASES = [
    ("load", "Load all four tables (rows/s, one transaction per batch)"),
    ("point_read", "Point read — order by primary key"),
    ("customer_orders", "Indexed lookup — a customer's orders"),
    ("order_detail", "3-table join — order → items → products"),
    ("revenue_by_city", "Join + GROUP BY — paid revenue by city"),
    ("refund_with_history", "Update, keeping the prior version (the refund wave)"),
    ("status_as_of", "Point-in-time read — status before the refund wave"),
    ("revenue_by_city_as_of", "Point-in-time join + GROUP BY — revenue before the refund wave"),
]
EMBEDDED = ["nedb", "sqlite"]
NETWORKED = ["nedbd", "postgres", "redis", "mongo"]


def rate(x: float) -> str:
    if x >= 1e6:
        return f"{x / 1e6:.2f}M/s"
    if x >= 1e3:
        return f"{x / 1e3:.1f}K/s"
    if x >= 10:
        return f"{x:.0f}/s"
    return f"{x:.2f}/s"


def lat(us: float) -> str:
    if us >= 1e6:
        return f"{us / 1e6:.2f} s"
    if us >= 1e3:
        return f"{us / 1e3:.2f} ms"
    return f"{us:.0f} µs"


def size(b: Optional[int]) -> str:
    if b is None:
        return "—"
    for unit in ("B", "KiB", "MiB", "GiB"):
        if b < 1024:
            return f"{b:.0f} {unit}" if unit == "B" else f"{b:.1f} {unit}"
        b /= 1024
    return f"{b:.1f} TiB"


def cell(r: Dict[str, Any], phase: str) -> str:
    st = r.get("status")
    if st == "n/a":
        return "N/A ¹"
    if st != "ok":
        return f"**{st.upper()}**"
    p = r["phases"].get(phase)
    if not p:
        return "—"
    s = rate(p["ops_per_s"])
    if "p99_us" in p:
        s += f"<br><sub>p50 {lat(p['p50_us'])} · p99 {lat(p['p99_us'])}</sub>"
    return s


def _ok(res, e):
    return res.get(e, {}).get("status") == "ok"


def standings(res: Dict[str, Any], labels: Dict[str, str], who: str, rivals: List[str]) -> List[str]:
    """Computed lead/trail lines for NEDB leg `who` against `rivals`."""
    lines = []
    if not _ok(res, who):
        return lines
    rivals = [r for r in rivals if _ok(res, r)]
    if not rivals:
        return lines
    for phase, title in PHASES:
        mine = res[who]["phases"][phase]["ops_per_s"]
        best_r = max(rivals, key=lambda r: res[r]["phases"][phase]["ops_per_s"])
        best = res[best_r]["phases"][phase]["ops_per_s"]
        if mine >= best:
            runner = best_r
            lines.append(f"- **leads** {title.split(' — ')[0].lower()}: {rate(mine)} vs "
                         f"{labels[runner]} {rate(best)} (**{mine / best:.2f}×**)")
        else:
            lines.append(f"- **trails** {title.split(' — ')[0].lower()}: {rate(mine)} vs "
                         f"{labels[best_r]} {rate(best)} ({best / mine:.2f}× behind)")
    return lines


def render(out: Dict[str, Any]) -> str:
    m = out["meta"]
    eng = out["engines"]
    labels = {e: v["label"] for e, v in eng.items()}
    order = [e for e in ["nedb", "sqlite", "nedbd", "postgres", "redis", "mongo"] if e in eng]
    L: List[str] = []
    w = L.append

    w("# Benchmarks — NEDB vs SQLite, PostgreSQL, Redis, MongoDB\n")
    w("> Generated by `bench/compare.py` from the on-demand **Benchmark (head-to-head)** workflow "
      "(`.github/workflows/bench-compare.yml`). Do not edit by hand — dispatch the workflow.\n")
    run = f" · [run]({m['run_url']})" if m.get("run_url") else ""
    w(f"**Date:** {m['date']} · **Commit:** `{m['commit']}`{run}  ")
    w(f"**Runner:** {m['runner']}  ")
    r = m["rows"]
    w(f"**Dataset:** {r['customers']:,} customers · {r['products']:,} products · {r['orders']:,} orders · "
      f"{r['order_items']:,} order items · refund wave of {m['refund_wave']:,} orders · load batch {m['batch']}\n")

    w("## The contract\n")
    w("Apples to apples means every engine gets the same work and is held to the same answer:\n")
    w("- **Same data.** One seeded dataset, handed byte-identical to every engine.")
    w("- **Same questions, same count, same order.** Each engine answers in its own idiomatic best form "
      "(SQL JOIN, `$lookup`, neSQL, or — for Redis, which has no join — a pipelined application-side join).")
    w("- **Same audit requirement.** *Keep every past version of an order, and answer what the data looked "
      "like before the refund wave.* NEDB does this natively. Every other engine gets it the way it is built "
      "in production — a history table in the same transaction, a history collection in a multi-document "
      "transaction, a history list inside `MULTI/EXEC` — and pays for it in the write path and in the query.")
    w("- **Same oracle.** Every answer is checked against the value computed from the seed in plain Python. "
      "A wrong answer fails the run. No engine is scored on a result it got wrong.")
    w("- **Matched durability, not shipped defaults.** `durable` = every commit on disk before the ack; "
      "`relaxed` = each engine's bounded (~1 s) loss-window mode. A leg that cannot honour a profile is "
      "**N/A**, never quietly run in a weaker mode.")
    w("- **Same client and machine.** One Python client process, one runner, engines run one after another. "
      "No foreign-key constraints on any engine, so none pays an integrity cost the others skip.\n")

    w("## Engines\n")
    w("| Engine | Version | Transport | durable | relaxed | Joins | History / AS OF | Integrity check |")
    w("|---|---|---|---|---|---|---|---|")
    for e in order:
        v = eng[e]
        ver = next((out["results"][p][e].get("version") for p in out["results"]
                    if out["results"][p].get(e, {}).get("version")), "—")
        d = v.get("durability", {})
        w(f"| {v['label']} | {ver} | {v['transport']} | {d.get('durable', '—')} | {d.get('relaxed', '—')} | "
          f"{v.get('join_model', '—')} | {v.get('history_model', '—')} | {v.get('integrity', 'none')} |")
    w("")
    if out.get("skipped"):
        w("**Skipped (not reachable on this run):** " +
          "; ".join(f"{labels.get(k, k)} — {v}" for k, v in out["skipped"].items()) + "\n")

    notes: Dict[str, str] = {}
    for profile, res in out["results"].items():
        w(f"## Profile: `{profile}`\n")
        cols = [e for e in order if e in res]
        w("| Operation | " + " | ".join(labels[e] for e in cols) + " |")
        w("|---|" + "---|" * len(cols))
        for phase, title in PHASES:
            w(f"| {title} | " + " | ".join(cell(res[e], phase) for e in cols) + " |")
        w("| Storage footprint | " + " | ".join(
            size(res[e].get("footprint_bytes")) if _ok(res, e) else "—" for e in cols) + " |")
        w("")
        for e in cols:
            if res[e].get("status") == "n/a":
                notes[f"{labels[e]} / {profile}"] = res[e]["reason"]
            elif res[e].get("status") not in ("ok",):
                w(f"> **{labels[e]} — {res[e]['status']}:** {res[e].get('reason')}\n")

        w(f"### Where NEDB stands — `{profile}` (computed from the table above)\n")
        emb = standings(res, labels, "nedb", ["sqlite"])
        if emb:
            w("**Embedded class — NEDB (embedded) vs SQLite:**\n")
            L.extend(emb)
            w("")
        net = standings(res, labels, "nedbd", ["postgres", "redis", "mongo"])
        if net:
            w("**Networked class — NEDB (nedbd HTTP) vs the best of PostgreSQL / Redis / MongoDB:**\n")
            L.extend(net)
            w("")

        w("**The cost of remembering** — how much slower each engine answers the *historical* "
          "revenue question than the *current* one (1.00× = history is free):\n")
        w("| Engine | current revenue_by_city | as of before the refund wave | multiplier |")
        w("|---|---|---|---|")
        for e in cols:
            if not _ok(res, e):
                continue
            a = res[e]["phases"]["revenue_by_city"]["ops_per_s"]
            b = res[e]["phases"]["revenue_by_city_as_of"]["ops_per_s"]
            w(f"| {labels[e]} | {rate(a)} | {rate(b)} | {a / b:.2f}× |")
        w("")
        integ = [(e, res[e].get("verify")) for e in cols if _ok(res, e)]
        w("**Integrity:** " + "; ".join(
            f"{labels[e]} — verify() **{'passed' if v['ok'] else 'FAILED'}** in {v['ms']:.1f} ms"
            if v else f"{labels[e]} — no built-in tamper-evidence check" for e, v in integ) + "\n")

    if notes:
        w("## Notes\n")
        for k, v in notes.items():
            w(f"¹ **{k}:** {v}  ")
        w("")

    w("## What this does and does not show\n")
    w("- Numbers are comparable **within one run**. GitHub runners are shared VMs; across runs, expect noise.")
    w("- Every engine is driven from Python, so client-side decode cost is in every number, for every engine alike.")
    w("- Embedded engines (NEDB embedded, SQLite) pay no socket hop. Compare them with each other, and compare "
      "the networked legs with each other — the tables are grouped for that reason.")
    w("- The point-in-time queries on the other engines assume no orders are inserted after the marker, "
      "which holds for this workload. NEDB's `AS OF SYSTEM TIME` has no such assumption.")
    w("- Re-run it yourself: **Actions → Benchmark (head-to-head) → Run workflow**, or locally with "
      "`python3 bench/compare.py --orders 5000 --markdown /tmp/BENCHMARKS.md` (unreachable servers are skipped, loudly).\n")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    data = json.load(open(sys.argv[1]))
    sys.stdout.write(render(data))
